### ISSUE TITLE
use FEVM-Hardhat-Kit deploy failed when wallaby reset 

### ISSUE THREAD

**Issue by imxyb** [filecoin-project/fevm-hardhat-kit#28]
I use FEVM-Hardhat-Kit to deploy smart contracts. Everything works fine before the network is reset, but after wallaby is reset, the following error will be returned:
![image](https://user-images.githubusercontent.com/7411249/206670995-4fe12ca9-d59b-468c-8205-08fd55bb28e3.png)

Only when I use another address to deploy can it succeed, what is the reason?

**Comment by ZakAyesh** [comment]
Could you provide the rest of the error? Most likely what is happening is that hardhat is looking through your deployments folder and looking for a contracts at the addresses stored there, but since Wallaby has been reset those contracts no longer exist on chain. If that is the case you can run the command yarn hardhat deploy --reset
